name: LEventos
version: '1.1'
main: com.uaulight.leventos.Main
authors: [ uauLight ]
description: Plugin de Eventos para o seru servidor.
website: https://skymc.com.br/
commands:
  evento:
    aliases: [eventos,event,events,leventos]
  bolao:
  loteria: